'strict mode'

var Q;
var L;

window.onload = function(argument) {
	
	var questHTML = document.getElementById('content');
	var item;
	L = new list_ui({
		parent: questHTML,
		iterator: false,
		maxWidth: 1000
	})
	console.log(bar);
	
	var objectClickTest = JSON.parse('{"xName":"Question","xId":"CTest","xType":"Text","xHint":"С помощью мышки кликните на нужные слова или изображения. Для отмены выделения снова кликните по выделенному элементу.","xHeader":"<div class=\\\"small-hint\\\"><span class=\\\"q-num\\\">2.13.</span> ClickTest. Точечный</div>Посмотрите на это изображение. При помощи мышки отметьте 3 точки, которые привлекли Ваше внимание, неважно, нравится Вам то, что там изображено, или нет.","children":[{"xName":"Ui","xExtend":"ClickTest","xSrc":"https://www.123.ru/imgs/banners/banner_5d25ae157fe97.jpg"},{"xName":"Repeat","xLength":"5"},{"xName":"Answer","xId":"1","xText":"1. Ответ #1"},{"xName":"Answer","xId":"2","xText":"2. Ответ #2"},{"xName":"Answer","xId":"3","xText":"3. Ответ #3"},{"xName":"Answer","xId":"4","xText":"4. Ответ #4"},{"xName":"Answer","xId":"5","xText":"5. Ответ #5"},{"xName":"Answer","xId":"99","xReset":"true","xText":"Ничего"},{"xName":"Answer","xId":"999","xReset":"true","xText":"Ничего"}]}');
	var objectClickText = JSON.parse('{"xName":"Question","xId":"CT","xType":"Text","xHint":"С помощью мышки кликните на нужные слова или изображения. Для отмены выделения снова кликните по выделенному элементу.","xHeader":"<div class=\\\"small-hint\\\"><span class=\\\"q-num\\\">2.11.</span> ClickTest. Текстовый</div>Внимательно прочитайте описание концепции и отметьте те слова или изображения, которые <u>понравились Вам больше всего</u>.","children":[{"xName":"Ui","xExtend":"ClickText","xSelectedFontColor":"black","xSelectedBackgroundColor":"orange","xSplittingType":"1"},{"xName":"Answer","xId":"1","xText":"<div class=\\\"ct-box brd\\\"><h2 class=\\\"c\\\">Несколько интересных фактов о шоколаде</h2><div class=\\\"ct-container f-c\\\"><div><img src=\'http://fitfan.ru/uploads/posts/2010-10/1286905967_milk_chocolate.jpg\'/></div><div><p>В Париже каждый год проводятся \\\"{Шоколадные салоны}\\\", на которых демонстрируются наряды и аксессуары к ним, изготовленные из шоколада. В Нью-Йорке известными модельерами был устроен показ вечерних туалетов, изготовленных из разных сортов шоколада.</p><p>В 2004 году в итальянском городе Перуджа на фестивале шоколада был представлен \\\"Камакао\\\" - мощный афродизиак, который представляет собой шоколад с добавлением имбиря. На каждой упаковке \\\"Камакао\\\" изображены сцены из На выставке в Милане канадская бельевая компания продемонстрировала шоколадный бюстгальтер, изготовленный ею совместно с бельгийскими кондитерами.<br>На украинском рынке появилась новинка - 30-граммовый батончик под названием {\\\"Сало в шоколаде\\\"}. В этом изделии помимо какао-бобов, сахара и ароматизаторов содержатся жир, спирт и соль.</div></div></div>"},{"xName":"Answer","xId":"99","xReset":"true","xText":"Нет такого"}]}');
	var objectCombo = JSON.parse('{"xName":"Question","xId":"Q61","xType":"CheckBox","xHeader":"Ползунок","children":[{"xName":"Ui","xExtend":"ComboBox"},{"xName":"Repeat","xLength":"10"},{"xName":"Answer","xId":"1","xText":"Помню очень нечетко"},{"xName":"Answer","xId":"2","xText":"2"},{"xName":"Answer","xId":"99","xReset":"True","xText":"Reset"},{"xName":"Answer","xId":"3","xText":"3"},{"xName":"Answer","xId":"4","xText":"4"},{"xName":"Answer","xId":"5","xText":"5"},{"xName":"Answer","xId":"6","xText":"6"},{"xName":"Answer","xId":"7","xText":"7"},{"xName":"Answer","xId":"8","xText":"8"},{"xName":"Answer","xId":"9","xText":"Совсем не помню"},{"xName":"Answer","xId":"10","xText":"Помню в подробностях"}]}');
//	objectCombo = JSON.parse('{"xName":"Question","xId":"Q61","xHeader":"Ползунок","children":[{"xName":"Ui","xExtend":"ComboBox"},{"xName":"Repeat","xLength":"10"},{"xName":"Answer","xId":"1","xText":"Помню очень нечетко"},{"xName":"Answer","xId":"2","xText":"2"},{"xName":"Answer","xId":"3","xText":"3"},{"xName":"Answer","xId":"4","xText":"4"},{"xName":"Answer","xId":"5","xText":"5"},{"xName":"Answer","xId":"6","xText":"6"},{"xName":"Answer","xId":"7","xText":"7"},{"xName":"Answer","xId":"8","xText":"8"},{"xName":"Answer","xId":"9","xText":"Совсем не помню"},{"xName":"Answer","xId":"10","xText":"Помню в подробностях"}]}');
	
//	var objectLine = JSON.parse('{"xName":"Question","xId":"Q11","xType":"RadioButton","xHint":"Один ответ","xHeader":"Список","children":[{"xName":"Answer","xId":"1","xText":"A"},{"xName":"Answer","xId":"2","xText":"B"},{"xName":"Answer","xId":"3","xText":"C"},{"xName":"Answer","xId":"4","xText":"D"},{"xName":"Answer","xId":"5","xText":"E"}]}');
	var objectLine = JSON.parse('{"xName":"Question","xId":"Q11","xType":"Text","xTextWidth":"30","xEndTextWidth":"30","xHint":"Один ответ","xHeader":"Список","children":[{"xName":"Answer","xId":"1","xEndText":"%","xText":""},{"xName":"Answer","xTitle":"Hello","xEndText":"%","xId":"2","xText":"B"},{"xName":"Answer","xId":"3","xText":"C"},{"xName":"Answer","xType":"Text","xId":"4","xText":"D"},{"xName":"Answer","xReset":"True","xId":"5","xText":"E"},{"xName":"Answer","xIsolate":"1","xId":"6","xText":"isol"}]}');
	var objectTable = JSON.parse('{"xName":"Question","xEndText":"%","xId":"Q23","xVisible":"false","xOrientation":"Vertical","xUnion":"Q23_1,Q23_2,Q23_3,Q23_4","xHint":"Разные типы","xHeader":"Таблица","children":[{"xName":"Holder","xAlign":"left","xInnerText":"SomeBodyToldYou"},{"xName":"UI","xHeaderFix":"1"},{"xName":"Answer","xId":"1","xText":"A"},{"xName":"Answer","xId":"2","xTitle":"whatarofl","xText":"B"},{"xName":"Answer","xId":"3","xText":"C"},{"xName":"Answer","xId":"4","xText":"D","xType":"Text"},{"xName":"Answer","xId":"5","xReset":"True","xText":"E"},{"xName":"Answer","xId":"6","xReset":"True","xText":"F"}],"union":[{"xName":"Question","xId":"Q23_1","xType":"CheckBox","xText":"Sub1"},{"xName":"Question","xId":"Q23_2","xType":"RadioButton","xText":"Sub2"},{"xName":"Question","xId":"Q23_3","xType":"RadioButton","xText":"Sub3"},{"xName":"Question","xId":"Q23_4","xType":"Text","xText":"Sub4"}]}');
	var objectCheck = JSON.parse('{"xName":"Question","xId":"Q11","xType":"CheckBox","xOrientation":"Horizontal","xHint":"Один ответ","xHeader":"Список","children":[{"xName":"Answer","xId":"1","xText":"A"},{"xName":"Answer","xId":"2","xText":"B"},{"xName":"Answer","xId":"3","xText":"C"},{"xName":"Answer","xId":"4","xText":"D"},{"xName":"Answer","xId":"5","xText":"E"}]}');
	var objectText = JSON.parse('{"xName":"Question","xId":"Q11","xType":"Text","xHint":"Один ответ","xHeader":"Список","children":[{"xName":"Answer","xId":"1","xType":"Text","xText":"A"},{"xName":"Answer","xId":"2","xText":"B"},{"xName":"Answer","xId":"3","xText":"C"},{"xName":"Answer","xId":"4","xText":"D"},{"xName":"Answer","xId":"5","xReset":"True","xText":"E"}]}');
	var objectMemo = JSON.parse('{"xName":"Question","xEndText":"%","xId":"Q11","xType":"Memo","xHint":"Один ответ","xOrientation":"Horizontal","xHeader":"Список","children":[{"xName":"Answer","xId":"1","xText":"A"},{"xName":"Answer","xId":"2","xText":"B"},{"xName":"Answer","xId":"3","xText":"C"},{"xName":"Answer","xId":"4","xText":"D"},{"xName":"Answer","xId":"5","xText":"E"}]}');
	var objectNumber = JSON.parse('{"xName":"Question","xId":"Q11","xType":"Number","xHint":"Один ответ","xOrientation":"Horizontal","xHeader":"Список","children":[{"xName":"Answer","xId":"1","xText":"A"},{"xName":"Answer","xEndText":"%","xId":"2","xText":"B"},{"xName":"Answer","xEndText":"%","xId":"3","xText":"C"},{"xName":"Answer","xEndText":"%","xId":"4","xText":"D"},{"xName":"Answer","xEndText":"%","xId":"5","xText":"E"}]}');
	var objectInteger = JSON.parse('{"xName":"Question","xId":"Q11","xType":"Integer","xHint":"Один ответ","xOrientation":"Horizontal","xHeader":"Список","children":[{"xName":"Answer","xId":"1","xText":"A"},{"xName":"Answer","xId":"2","xText":"B"},{"xName":"Answer","xId":"3","xText":"C"},{"xName":"Answer","xId":"4","xText":"D"},{"xName":"Answer","xId":"5","xText":"E"}]}');
	var objectScale = JSON.parse('{	"xName":"Question",	"xId":"Q51",	"xHeader":"Шкала",	"children":[		{"xName":"Holder","xAlign":"left","xInnerText":"SomeBodyToldYou"},		{"xName":"Ui","xExtend":"Scale","xLabelStart":"Совсем не нравится","xLabelEnd":"Очень нравится"},		{"xName":"Repeat","xLength":"10"},		{"xName":"Answer","xId":"1","xText":"1"},		{"xName":"Answer","xId":"2","xText":"2"},		{"xName":"Answer","xId":"3","xText":"3"},		{"xName":"Answer","xId":"4","xText":"4"},		{"xName":"Answer","xId":"5","xText":"5"},		{"xName":"Answer","xId":"6","xText":"6"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"9","xText":"9"},		{"xName":"Answer","xId":"10","xText":"10"},		{"xName":"Answer","xId":"99","xText":"Forgot al","xReset":"True"}	]}');
	var objectScale2 = JSON.parse('{	"xName":"Question",	"xId":"Q51",	"xHeader":"Шкала",	"children":[		{"xName":"Holder","xAlign":"left","xInnerText":"SomeBodyToldYou"},		{"xName":"Ui","xExtend":"Scale","xGradient":"True","xGradientColors":"​​rgba(250,5,200,0.5);rgba(250,200,200,0.5);rgba(250,250,5,0.5);rgba(5,5,250,0.5);rgba(200,200,200,0.5);rgba(50,200,50,0.5)","xLabelStart":"Совсем не нравится","xLabelEnd":"Очень нравится"},		{"xName":"Repeat","xLength":"10"},		{"xName":"Answer","xId":"1","xText":"1"},	{"xName":"Answer","xId":"1","xText":"1"},	{"xName":"Answer","xId":"2","xText":"2"},		{"xName":"Answer","xId":"3","xText":"3"},		{"xName":"Answer","xId":"4","xText":"4"},		{"xName":"Answer","xId":"5","xText":"5"},		{"xName":"Answer","xId":"6","xText":"6"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"7","xText":"7"},		{"xName":"Answer","xId":"8","xText":"8"},		{"xName":"Answer","xId":"9","xText":"9"},		{"xName":"Answer","xId":"10","xText":"10"},		{"xName":"Answer","xId":"99","xText":"Forgot al","xReset":"True"}	]}');
	var objectContentOnly = JSON.parse('{"xName":"Question","xId":"Q41","xType":"CheckBox","xHint":"Один ответ","xHeader":"Плитка","children":[{"xName":"Ui","xCols":"11","xExtend":"ContentOnly"},{"xName":"Answer","xId":"1","xText":"A"},{"xName":"Answer","xId":"2","xText":"B"},{"xName":"Answer","xId":"3","xText":"C"},{"xName":"Answer","xId":"4","xText":"D"},{"xName":"Answer","xId":"5","xText":"E"},{"xName":"Answer","xId":"6","xText":"F"},{"xName":"Answer","xId":"7","xText":"G"},{"xName":"Answer","xId":"8","xText":"H"},{"xName":"Answer","xId":"9","xText":"I"},{"xName":"Answer","xId":"10","xText":"J"},{"xName":"Answer","xId":"11","xText":"K"},{"xName":"Answer","xId":"12","xText":"L"},{"xName":"Answer","xId":"13","xText":"M"},{"xName":"Answer","xId":"14","xText":"N"},{"xName":"Answer","xId":"15","xText":"O"},{"xName":"Answer","xId":"16","xText":"P"},{"xName":"Answer","xId":"17","xText":"Q"},{"xName":"Answer","xId":"18","xText":"R"},{"xName":"Answer","xId":"19","xText":"S"}]}');
	var objectDragItem = JSON.parse('{"xName":"Question","xId":"Q71","xVisible":"false","xTextWidth":"50","xUnionMix":"true","xHint":"Перетащите места в соответствующие коробочки","xUnion":"Q71_1,Q71_2,Q71_3","xHeader":"Как часто за последние 6 месяцев Вы бывали в следующих местах?","children":[{"xName":"Ui","xExtend":"DragItem","xTargetContainer":"400,100","xType":"Range","xHeaderFix":"1"},{"xName":"Answer","xId":"1","xText":"1 раз в неделю и чаще"},{"xName":"Answer","xId":"2","xText":"2-3 раза в месяц"},{"xName":"Answer","xId":"3","xText":"1 раз в месяц"},{"xName":"Answer","xId":"4","xText":"3-4 раза в полгода"},{"xName":"Answer","xId":"4","xText":"3-4 раза в полгода"},{"xName":"Answer","xId":"8","xText":"1-2 раза в полгода и реже"},{"xName":"Answer","xId":"7","xText":"Ни разу"}],"union":[{"xName":"Question","xId":"Q71_1","xType":"RadioButton","xText":"Раздевалка"},{"xName":"Question","xId":"Q71_2","xType":"RadioButton","xText":"Кухня 2Кухня 2Кухня 2Кухня 2Кухня "},{"xName":"Question","xId":"Q71_3","xType":"RadioButton","xText":"Кухня 2"},{"xName":"Question","xId":"Q71_3","xType":"RadioButton","xText":"Кухня 2"},{"xName":"Question","xId":"Q71_3","xType":"RadioButton","xText":"5"},{"xName":"Question","xId":"Q71_3","xType":"RadioButton","xText":"6"},{"xName":"Question","xId":"Q71_3","xType":"RadioButton","xText":"7"},{"xName":"Question","xId":"Q71_3","xType":"RadioButton","xText":"8"},{"xName":"Question","xId":"Q71_3","xType":"RadioButton","xText":"9"}]}');
	var object3 = JSON.parse('{"xName":"Question","xId":"Q23","xVisible":"false","xUnion":"Q23_1,Q23_2,Q23_3,Q23_4","xHint":"Разные типы","xHeader":"Таблица","children":[{"xName":"Answer","xId":"1","xText":"A"},{"xName":"Answer","xId":"2","xText":"B"},{"xName":"Answer","xId":"3","xText":"C"},{"xName":"Answer","xId":"4","xText":"D"},{"xName":"Answer","xId":"5","xText":"E"}],"union":[{"xName":"Question","xId":"Q23_1","xType":"CheckBox","xText":"Sub1"},{"xName":"Question","xId":"Q23_2","xType":"RadioButton","xText":"Sub2"},{"xName":"Question","xId":"Q23_3","xType":"RadioButton","xText":"Sub3"},{"xName":"Question","xId":"Q23_4","xType":"Text","xText":"Sub4"}]}');
	var object6 = JSON.parse('{"xName":"Question","xId":"Q71","xVisible":"false","xTextWidth":"50","xUnionMix":"true","xHint":"Перетащите места в соответствующие коробочки","xUnion":"Q71_1,Q71_2,Q71_3","xHeader":"Как часто за последние 6 месяцев Вы бывали в следующих местах?","children":[{"xName":"Ui","xExtend":"DragItem","xTargetContainer":"400,100","xType":"Card","xHeaderFix":"1"},{"xName":"Answer","xId":"1","xText":"1 раз в неделю и чаще"},{"xName":"Answer","xId":"2","xText":"2-3 раза в месяц"},{"xName":"Answer","xId":"3","xText":"1 раз в месяц"},{"xName":"Answer","xId":"4","xText":"3-4 раза 3-4 раза 3-4 раза 3-4 Раздевалка3-4 раза 3-4 раза 3-4 раза в полгода"},{"xName":"Answer","xId":"4","xText":"3-4 раза в полгода"},{"xName":"Answer","xId":"8","xText":"1-2 раза в полгода и реже"},{"xName":"Answer","xId":"7","xText":"Ни разу"}],"union":[{"xName":"Question","xId":"Q71_1","xType":"RadioButton","xText":"Раздевалка"},{"xName":"Question","xId":"Q71_2","xType":"RadioButton","xText":"Кухня 2Кухня 2Кухня 2Кухня 2Кухня "},{"xName":"Question","xId":"Q71_3","xType":"RadioButton","xText":"Кухня 2"},{"xName":"Question","xId":"Q71_3","xType":"RadioButton","xText":"Кухня 2"},{"xName":"Question","xId":"Q71_3","xType":"RadioButton","xText":"5"},{"xName":"Question","xId":"Q71_3","xType":"RadioButton","xText":"6"},{"xName":"Question","xId":"Q71_3","xType":"RadioButton","xText":"7"},{"xName":"Question","xId":"Q71_3","xType":"RadioButton","xText":"8"},{"xName":"Question","xId":"Q71_3","xType":"RadioButton","xText":"s dfsd f sdf sdf sdf sdfsd fsddfsfsd fsdfds d sf sdfsdf  sdfsdf9"}]}');

	var objectVideo = JSON.parse('{"xName":"Question","xId":"Q1_1","xType":"Text","xHint":"","xHeader":"Плеер<br/>Посмотрите на этот ролик. После просмотра появится вопрос.","children":[{"xName":"Ui","xExtend":"MediaPlayer","xType":"Video","xButtonLikeEnable":"1","xButtonDislikeEnable":"1","xButtonBoringEnable":"1","xSrc":"example/oceans.mp4"},{"xName":"Answer","xId":"1","xText":"Like"},{"xName":"Answer","xId":"2","xText":"Dislike"},{"xName":"Answer","xId":"3","xText":"Boring"}]}');
	var objectSlider = JSON.parse('{"xName":"Question","xId":"Q11","xType":"RadioButton","union":[{"xName":"Question","xId":"Q23_1","xType":"CheckBox","xText":"Sub1"},{"xName":"Question","xId":"Q23_2","xType":"RadioButton","xText":"Sub2"},{"xName":"Question","xId":"Q23_3","xType":"RadioButton","xText":"Sub3"},{"xName":"Question","xId":"Q23_4","xType":"Text","xText":"Sub4"}],"xTextWidth":"30","xEndTextWidth":"30","xHint":"Один ответ","xHeader":"Список","children":[{"xName":"Ui","xExtend":"Slider","xValueShow":"True","xValueShowSelected":"True"},{"xName":"Answer","xId":"1","xEndText":"%","xText":""},{"xName":"Answer","xEndText":"%","xId":"2","xText":"B"},{"xName":"Answer","xId":"3","xText":"C"},{"xName":"Answer","xType":"Text","xId":"4","xText":"D"},{"xName":"Answer","xReset":"True","xId":"5","xText":"E"}]}');

	var container = document.getElementsByClassName('pvb-viewport')[0];
	var itemarray = [];

	
	item = L.addItems({text: ''})[0].preview;
	Q = new question_ui({
		parent: item,
		object: objectScale
	});
	itemarray.push( [ item, Q ] );



	for(var i = 0; i < 10; i++){
		item = L.addItems({text: ''})[0].preview;
		Q = new question_ui({
			parent: item,
			object: objectTable
		});
		itemarray.push( [ item, Q] );
	}

	
	

	container.onscroll = function(){
		var topscroll = container.scrollTop;
		itemarray.forEach(function(item){
			var top = item[0].parentNode.parentNode.parentNode.offsetTop;
			item[1].moveHeaderFix(topscroll, top);
		})		
	}
}